version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: spare-parts-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spare_parts_pos
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
