name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: team_emFEjso4w4GpBnHXldl4bWMm
      VERCEL_PROJECT_ID: prj_kuuRyUPyElTAEN7xjj0aC8zrbJ7e
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --cwd=backend
      - run: npx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd=backend

  deploy-frontend:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: team_emFEjso4w4GpBnHXldl4bWMm
      VERCEL_PROJECT_ID: prj_ASGlwTyyBu8eADafetUURi6JIK1B
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --cwd=web
      - run: npx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd=web
